on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test XVFB
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: echo 'Testing xvfb'
      - name: Test XVFB with working directory
        uses: GabrielBB/xvfb-action@v1.6
        with:
          working-directory: ./node_modules
          run: pwd
      - name: Test XVFB with options
        uses: GabrielBB/xvfb-action@v1.6
        with:
          options: -screen 0 1600x1200x24
          run: echo 'Testing xvfb'
      - name: Test using major tag
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./node_modules
          options: -screen 0 1600x1200x24
          run: pwd
